// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package go_micro_srv_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubmitRequest struct {
	ProductId            uint32   `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Uid                  uint32   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_b240543da7d1d6b1, []int{0}
}
func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}
func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}
func (dst *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(dst, src)
}
func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}
func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

func (m *SubmitRequest) GetProductId() uint32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *SubmitRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SubmitRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type Response struct {
	Ode                  string   `protobuf:"bytes,1,opt,name=ode,proto3" json:"ode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_b240543da7d1d6b1, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOde() string {
	if m != nil {
		return m.Ode
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type OrderDetailRequest struct {
	OrdeId               string   `protobuf:"bytes,1,opt,name=ordeId,proto3" json:"ordeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetailRequest) Reset()         { *m = OrderDetailRequest{} }
func (m *OrderDetailRequest) String() string { return proto.CompactTextString(m) }
func (*OrderDetailRequest) ProtoMessage()    {}
func (*OrderDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_b240543da7d1d6b1, []int{2}
}
func (m *OrderDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailRequest.Unmarshal(m, b)
}
func (m *OrderDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailRequest.Marshal(b, m, deterministic)
}
func (dst *OrderDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailRequest.Merge(dst, src)
}
func (m *OrderDetailRequest) XXX_Size() int {
	return xxx_messageInfo_OrderDetailRequest.Size(m)
}
func (m *OrderDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailRequest proto.InternalMessageInfo

func (m *OrderDetailRequest) GetOrdeId() string {
	if m != nil {
		return m.OrdeId
	}
	return ""
}

func init() {
	proto.RegisterType((*SubmitRequest)(nil), "go.micro.srv.order.SubmitRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.order.Response")
	proto.RegisterType((*OrderDetailRequest)(nil), "go.micro.srv.order.OrderDetailRequest")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor_order_b240543da7d1d6b1) }

var fileDescriptor_order_b240543da7d1d6b1 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x5d, 0x8b, 0x8b, 0x3b, 0x5a, 0x90, 0x41, 0x74, 0x91, 0x1e, 0x34, 0x07, 0xf1, 0x20,
	0x11, 0xf4, 0x15, 0xbc, 0x88, 0x07, 0x21, 0xa5, 0x0f, 0x60, 0x93, 0xa1, 0x04, 0xdc, 0xce, 0x9a,
	0x3f, 0x7d, 0x30, 0x9f, 0x50, 0x32, 0xdb, 0xa2, 0xd2, 0x05, 0x2f, 0x61, 0xe6, 0x9b, 0x8f, 0x8f,
	0xdf, 0x47, 0xe0, 0xb2, 0x0f, 0x9c, 0xf8, 0x81, 0x83, 0xa3, 0x30, 0xbc, 0x5a, 0x14, 0xc4, 0x15,
	0xeb, 0xce, 0xdb, 0xc0, 0x3a, 0x86, 0x8d, 0x96, 0x8b, 0x5a, 0xc0, 0x74, 0x9e, 0x97, 0x9d, 0x4f,
	0x86, 0x3e, 0x33, 0xc5, 0x84, 0x33, 0x68, 0xfa, 0xc0, 0x2e, 0xdb, 0xf4, 0xe2, 0xda, 0xea, 0xba,
	0xba, 0x9b, 0x9a, 0x1f, 0x01, 0xcf, 0xe1, 0xc8, 0x72, 0x5e, 0xa7, 0xf6, 0x50, 0x2e, 0xc3, 0x82,
	0x67, 0x30, 0xc9, 0xde, 0xb5, 0x13, 0xd1, 0xca, 0xa8, 0x34, 0x1c, 0x1b, 0x8a, 0x3d, 0xaf, 0x23,
	0x95, 0x2b, 0x3b, 0x92, 0xac, 0xc6, 0x94, 0xb1, 0x28, 0x5d, 0x5c, 0x49, 0x46, 0x63, 0xca, 0xa8,
	0xee, 0x01, 0xdf, 0x0a, 0xcf, 0x33, 0xa5, 0x77, 0xff, 0xb1, 0x63, 0xb9, 0x80, 0xba, 0x50, 0x6e,
	0x41, 0x1a, 0xb3, 0xdd, 0x1e, 0xbf, 0x2a, 0x38, 0x15, 0xfb, 0x9c, 0xc2, 0xc6, 0x5b, 0xc2, 0x57,
	0xa8, 0x87, 0x16, 0x78, 0xa3, 0xf7, 0x4b, 0xea, 0x3f, 0x0d, 0xaf, 0x66, 0x63, 0x96, 0x1d, 0xad,
	0x3a, 0xc0, 0x05, 0x9c, 0xfc, 0x62, 0xc1, 0xdb, 0x31, 0xfb, 0x3e, 0xec, 0x7f, 0xb1, 0xcb, 0x5a,
	0x3e, 0xe1, 0xe9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x28, 0x01, 0x5a, 0x50, 0x9f, 0x01, 0x00, 0x00,
}
