// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package go_micro_srv_product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Intor                string   `protobuf:"bytes,3,opt,name=intor,proto3" json:"intor,omitempty"`
	Number               uint32   `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_b6c5d95c8d39410f, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetIntor() string {
	if m != nil {
		return m.Intor
	}
	return ""
}

func (m *Product) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SerchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerchRequest) Reset()         { *m = SerchRequest{} }
func (m *SerchRequest) String() string { return proto.CompactTextString(m) }
func (*SerchRequest) ProtoMessage()    {}
func (*SerchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_b6c5d95c8d39410f, []int{1}
}
func (m *SerchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerchRequest.Unmarshal(m, b)
}
func (m *SerchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerchRequest.Marshal(b, m, deterministic)
}
func (dst *SerchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerchRequest.Merge(dst, src)
}
func (m *SerchRequest) XXX_Size() int {
	return xxx_messageInfo_SerchRequest.Size(m)
}
func (m *SerchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SerchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SerchRequest proto.InternalMessageInfo

func (m *SerchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SerchResponse struct {
	Code                 string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Product              []*Product `protobuf:"bytes,3,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SerchResponse) Reset()         { *m = SerchResponse{} }
func (m *SerchResponse) String() string { return proto.CompactTextString(m) }
func (*SerchResponse) ProtoMessage()    {}
func (*SerchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_b6c5d95c8d39410f, []int{2}
}
func (m *SerchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerchResponse.Unmarshal(m, b)
}
func (m *SerchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerchResponse.Marshal(b, m, deterministic)
}
func (dst *SerchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerchResponse.Merge(dst, src)
}
func (m *SerchResponse) XXX_Size() int {
	return xxx_messageInfo_SerchResponse.Size(m)
}
func (m *SerchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SerchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SerchResponse proto.InternalMessageInfo

func (m *SerchResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SerchResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SerchResponse) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DetailRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_b6c5d95c8d39410f, []int{3}
}
func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (dst *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(dst, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DetailResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Product              *Product `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_b6c5d95c8d39410f, []int{4}
}
func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (dst *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(dst, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DetailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DetailResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type ReduceNumberRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceNumberRequest) Reset()         { *m = ReduceNumberRequest{} }
func (m *ReduceNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ReduceNumberRequest) ProtoMessage()    {}
func (*ReduceNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_b6c5d95c8d39410f, []int{5}
}
func (m *ReduceNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceNumberRequest.Unmarshal(m, b)
}
func (m *ReduceNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceNumberRequest.Marshal(b, m, deterministic)
}
func (dst *ReduceNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceNumberRequest.Merge(dst, src)
}
func (m *ReduceNumberRequest) XXX_Size() int {
	return xxx_messageInfo_ReduceNumberRequest.Size(m)
}
func (m *ReduceNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceNumberRequest proto.InternalMessageInfo

func (m *ReduceNumberRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReduceNumberResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceNumberResponse) Reset()         { *m = ReduceNumberResponse{} }
func (m *ReduceNumberResponse) String() string { return proto.CompactTextString(m) }
func (*ReduceNumberResponse) ProtoMessage()    {}
func (*ReduceNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_b6c5d95c8d39410f, []int{6}
}
func (m *ReduceNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceNumberResponse.Unmarshal(m, b)
}
func (m *ReduceNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceNumberResponse.Marshal(b, m, deterministic)
}
func (dst *ReduceNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceNumberResponse.Merge(dst, src)
}
func (m *ReduceNumberResponse) XXX_Size() int {
	return xxx_messageInfo_ReduceNumberResponse.Size(m)
}
func (m *ReduceNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceNumberResponse proto.InternalMessageInfo

func (m *ReduceNumberResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ReduceNumberResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "go.micro.srv.product.Product")
	proto.RegisterType((*SerchRequest)(nil), "go.micro.srv.product.SerchRequest")
	proto.RegisterType((*SerchResponse)(nil), "go.micro.srv.product.SerchResponse")
	proto.RegisterType((*DetailRequest)(nil), "go.micro.srv.product.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "go.micro.srv.product.DetailResponse")
	proto.RegisterType((*ReduceNumberRequest)(nil), "go.micro.srv.product.ReduceNumberRequest")
	proto.RegisterType((*ReduceNumberResponse)(nil), "go.micro.srv.product.ReduceNumberResponse")
}

func init() {
	proto.RegisterFile("proto/product/product.proto", fileDescriptor_product_b6c5d95c8d39410f)
}

var fileDescriptor_product_b6c5d95c8d39410f = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xff, 0x40, 0xff, 0x34, 0x8e, 0x6d, 0x63, 0xc6, 0xc6, 0x90, 0x1a, 0x23, 0x59, 0x35,
	0x41, 0x0f, 0x6b, 0x52, 0x0f, 0x5e, 0x3c, 0x7a, 0x36, 0x06, 0xe2, 0xc9, 0x53, 0xbb, 0x6c, 0x70,
	0x13, 0x61, 0x71, 0x81, 0x7e, 0x23, 0xbf, 0xa7, 0x61, 0x59, 0xb0, 0x35, 0xb4, 0xb1, 0x9e, 0x98,
	0x5d, 0x7e, 0x33, 0xf3, 0xde, 0x23, 0xc0, 0x69, 0xae, 0x64, 0x29, 0x6f, 0x73, 0x25, 0xe3, 0x8a,
	0x95, 0xed, 0x93, 0xea, 0x5b, 0x9c, 0x26, 0x92, 0xa6, 0x82, 0x29, 0x49, 0x0b, 0xb5, 0xa2, 0xe6,
	0x1d, 0x79, 0x85, 0xe1, 0x73, 0x53, 0xe2, 0x04, 0x6c, 0x11, 0x7b, 0x96, 0x6f, 0x05, 0xe3, 0xd0,
	0x16, 0x31, 0x22, 0x0c, 0xb2, 0x45, 0xca, 0x3d, 0xdb, 0xb7, 0x82, 0x83, 0x50, 0xd7, 0x38, 0x85,
	0xff, 0x22, 0x2b, 0xa5, 0xf2, 0x1c, 0x7d, 0xd9, 0x1c, 0xf0, 0x04, 0xdc, 0xac, 0x4a, 0x97, 0x5c,
	0x79, 0x03, 0xdd, 0x6d, 0x4e, 0x84, 0xc0, 0x28, 0xe2, 0x8a, 0xbd, 0x85, 0xfc, 0xa3, 0xe2, 0x45,
	0xd9, 0x4d, 0xb4, 0xbe, 0x27, 0x92, 0x0c, 0xc6, 0x86, 0x29, 0x72, 0x99, 0x15, 0xbc, 0x86, 0x98,
	0x8c, 0x3b, 0xa8, 0xae, 0xf1, 0x08, 0x9c, 0xb4, 0x48, 0x8c, 0x92, 0xba, 0xc4, 0x7b, 0x18, 0x1a,
	0x0b, 0x9e, 0xe3, 0x3b, 0xc1, 0xe1, 0xfc, 0x8c, 0xf6, 0xf9, 0xa3, 0xc6, 0x5c, 0xd8, 0xd2, 0xe4,
	0x1c, 0xc6, 0x8f, 0xbc, 0x5c, 0x88, 0xf7, 0x56, 0xd4, 0x0f, 0xdb, 0x44, 0xc2, 0xa4, 0x05, 0xfe,
	0xae, 0xc8, 0xda, 0x43, 0xd1, 0x15, 0x1c, 0x87, 0x3c, 0xae, 0x18, 0x7f, 0xd2, 0xa9, 0x6d, 0xd3,
	0xf5, 0x00, 0xd3, 0x4d, 0x6c, 0x1f, 0x75, 0xf3, 0x4f, 0x1b, 0x26, 0x66, 0x73, 0xc4, 0xd5, 0x4a,
	0x30, 0x8e, 0x11, 0xb8, 0x4d, 0xf2, 0x48, 0xfa, 0x95, 0xae, 0x7f, 0xbb, 0xd9, 0xc5, 0x4e, 0xa6,
	0xd1, 0x42, 0xfe, 0xe1, 0x0b, 0xb8, 0x4d, 0x7a, 0xb8, 0xa5, 0x61, 0x23, 0xfc, 0xd9, 0xe5, 0x6e,
	0xa8, 0x1b, 0x9b, 0xc0, 0x68, 0xdd, 0x3c, 0x5e, 0xf7, 0xf7, 0xf5, 0xe4, 0x38, 0xbb, 0xf9, 0x0d,
	0xda, 0x2e, 0x5a, 0xba, 0xfa, 0x67, 0xb9, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x73, 0x0c, 0x4f,
	0x10, 0x4b, 0x03, 0x00, 0x00,
}
